import VerifyAuth from "@/components/verifyauth/verifyauth"

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <VerifyAuth>
          {children}
        </VerifyAuth>
      </body>
    </html>
  )
}
